name: flopy_example
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- numpy
- pandas
- scipy
- xarray
- geopandas
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- rtree
- pyproj>=2.2
- pyshp
- netcdf4
- pytest
- pip
- pip:
  - gis-utils
  - flopy
  - sfrmaker
